var BoardConstants = {
  BOARDS_RECEIVED: "BOARDS_RECEIVED",
  BOARD_RECEIVED: "BOARD_RECEIVED",
  CARD_RECEIVED: "CARD_RECEIVED",
  MEMBERSHIP_RECEIVED: "MEMBERSHIP_RECEIVED"
};

module.exports = BoardConstants;
