var UIConstants = {
  EXPAND_DROP_BIN: "EXPAND_DROP_BIN",
  RESET_BINS: "RESET BINS",
  TOGGLE_USER_DROPDOWN: "TOGGLE_USER_DROPDOWN",
  TOGGLE_BOARDS_DROPDOWN: "TOGGLE_BOARDS_DROPDOWN"
};

module.exports = UIConstants;
